---
# Common role tasks
- include_tasks: packages.yml
- include_tasks: users.yml
- include_tasks: ssh.yml
- include_tasks: security.yml
- include_tasks: arm-support.yml

- name: Install basic packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - python3-setuptools
      - git
      - build-essential
      - htop
      - vim
      - tmux
      - net-tools
      - nfs-common
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Configure locale
  locale_gen:
    name: "{{ system_locale }}"
    state: present

- name: Set locale system wide
  copy:
    dest: /etc/default/locale
    content: 'LANG={{ system_locale }}
LC_ALL={{ system_locale }}
LANGUAGE={{ system_locale }}'
    owner: root
    group: root
    mode: '0644'

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  ignore_errors: yes
  register: swapoff_result

- name: Remove swap from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install Docker from Ubuntu repositories
  apt:
    name:
      - docker.io
      - containerd
    state: present
    update_cache: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Reboot if needed
  reboot:
    msg: "Reboot initiated by Ansible for applying system updates"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  async: 1
  poll: 0
  changed_when: false
