---
# Kubernetes Configuration
kubernetes_version: "1.28.0-00"
kubernetes_apt_key: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
kubernetes_apt_repository: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"

# Global configuration for the cluster
cluster_name: "OddJobCluster"
cluster_domain: "local"

# Network configuration
cluster_network: "192.168.5.0/24"
cluster_gateway: "192.168.5.1"

# Storage configuration
shared_storage_path: "/shared"
backup_path: "/backup"

# Security configuration
ssh_key_path: "~/.ssh/cluster_key"
enable_firewall: true

# Monitoring configuration
monitoring_enabled: true
log_level: "INFO"

# Android Cluster Configuration
cluster_coordinator_port: 8765
cluster_dashboard_port: 8080
android_sdk_path: "/opt/android-sdk"
cluster_coordinator_path: "/opt/cluster-coordinator"

# Kubernetes configuration
kubectl_version: "v1.28.0"
kubernetes_namespace: "android-cluster"

# Container Runtime (containerd)
containerd_version: "1.6.8-1"

# Network Configuration
pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

# SLURM Configuration
slurm_version: "22.05.9"
slurm_partition: "android"
slurm_job_timeout: "1-00:00:00"
mysql_root_password: "change_this_secure_password"
slurmdbd_password: "change_this_secure_password"

# JupyterHub Configuration
jupyterhub_namespace: "jupyter"
jupyterhub_version: "3.0.0"
jupyterhub_hostname: "jupyter.your-domain.com"

# Nginx Configuration
nginx_ingress_version: "1.8.0"

# Monitoring Stack
prometheus_version: "v0.62.0"
grafana_version: "6.40.1"

# System Configuration
system_locale: "en_US.UTF-8"
timezone: "UTC"

# Docker Configuration
docker_version: "5:27.1.1-1~ubuntu.25.04~plucky"
docker_compose_version: "2.12.2"

# GitHub Pages Configuration
github_user: "your-github-username"
github_repo: "your-repo-name"
github_token: "your-github-token"  # Store this in a vault

# Docker Hub Configuration
dockerhub_username: "your-dockerhub-username"
dockerhub_password: "your-dockerhub-password"  # Store this in a vault
