---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx as reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Create directory for site configurations
  file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create directory for SSL certificates
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Generate self-signed SSL certificate
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/nginx-selfsigned.key
    -out /etc/nginx/ssl/nginx-selfsigned.crt
    -subj "/CN={{ ansible_fqdn }}"
  args:
    creates: /etc/nginx/ssl/nginx-selfsigned.crt

- name: Create directory for static files
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create landing page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Enable and start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Configure firewall to allow HTTP and HTTPS
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80'
    - '443'
